version: "3.8"
services:
  mongo-user:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_user_data:/data/db

  mongo-order:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_order_data:/data/db

  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway:
    build: api-gateway
    depends_on:
      - mongo-user
      - mongo-order
      - rabbitmq
    environment:
      - USER_V1=http://user-service-v1:8000
      - USER_V2=http://user-service-v1:8000
      - ORDER_SERVICE=http://order-service:8000
      - P=1
    ports:
      - "8000:8000"

  event-system:
    build: event-system
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo-user:
        condition: service_started
      mongo-order:
        condition: service_started
    environment:
      - RABBIT_URI=amqp://guest:guest@rabbitmq/
      - RABBIT_EXCHANGE=user_events
      - RABBIT_ROUTING_KEY=user.update

  user-service-v1:
    build: user-service-v1
    depends_on:
      - mongo-user
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongo-user:27017
      - MONGO_DB=userdb
      - RABBIT_URI=amqp://guest:guest@rabbitmq/
      - RABBIT_EXCHANGE=user_events
      - RABBIT_ROUTING_KEY=user.update

  order-service:
    build: order-service
    depends_on:
      - mongo-order
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongo-order:27017
      - MONGO_DB=orderdb
      - RABBIT_URI=amqp://guest:guest@rabbitmq/
      - RABBIT_EXCHANGE=user_events
      - RABBIT_ROUTING_KEY=user.update

volumes:
  mongo_user_data:
  mongo_order_data:
